export enum NodeType {
    App = 'X-APP',
    Page = 'X-PAGE',
    Packages = 'X-PACKAGES',
    Variable = 'X-VARIABLE',
    Router = 'X-ROUTER',
    Type = 'X-TYPE',
    Service = 'X-SERVICE',
    Asset = 'X-ASSET',
    RouterRoute = 'X-ROUTE',
    Component = 'X-COMPONENT',
    If = 'X-IF',
    For = 'X-FOR',
    Element = 'ELEMENT',
    Text = '#text',
    ComponentProperty = 'X-PROPERTY',
    ComponentEvent = 'X-EVENT',
    ComponentInstance = 'X-COMPONENT-INSTANCE',
    PageContainer = 'X-PAGE-CONTAINER',
    Icon = 'X-ICON',
    Api = 'X-API',
    ApiEndpoint = 'X-ENDPOINT',
    ApiParameter = 'X-PARAMETER',
    ApiHeader = 'X-HEADER',
    ApiBody = 'X-BODY',
    ApiResponse = 'X-RESPONSE'
}
