packages:
  - apps/*
  - packages/*
  - packages/vorplex/*
overrides:
  '@vorplex/core': 'workspace:*'
  '@vorplex/web': 'workspace:*'
  '@types/chrome': '^0.0.326'
  '@types/formidable': '^3.4.1'
  '@types/mssql': '^9.1.5'
  '@types/node': '^25.2.3'
  '@types/pg': '^8.15.6'
  '@types/semver': '^7.7.1'
  '@types/ws': '^8.5.5'
  'esbuild-wasm': '0.25.12'
  'formidable': '^3.5.0'
  'jose': '^6.1.3'
  'mssql': '^11.0.1'
  'pg': '^8.16.3'
  'semver': '^7.7.3'
  'tsx': '^4.21.0'
  'vitest': '^3.0.5'
  'tslib': '^2.8.1'
  'typescript': '^5.9.3'
  'ws': '^8.13.0'
  'yaml': '^2.8.2'
