name: Publish
description: Publish packages to NPM

inputs:
  npm-token:
    description: NPM authentication token
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: https://registry.npmjs.org/

    - name: Publish packages
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
      run: npx tsx .github/scripts/publish.ts
